# Data Preprocessing Template

## Importing the libraries

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [4]:
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

## Splitting the dataset into the Training set and Test set

In [32]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [33]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [34]:
from sklearn.impute import SimpleImputer 


In [35]:
imputer = SimpleImputer(missing_values=np.nan, strategy='mean') 
imputer.fit(X[:, 1:3])

SimpleImputer(add_indicator=False, copy=True, fill_value=None,
              missing_values=nan, strategy='mean', verbose=0)

In [36]:
X[:, 1:3] = imputer.transform(X[:, 1:3])


In [37]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## encoding the independent variable 


In [38]:
from sklearn.compose import ColumnTransformer 
from sklearn.preprocessing import OneHotEncoder 
ct = ColumnTransformer(transformers=[('endcoder', OneHotEncoder(),[0])], remainder='passthrough')
x = np.array(ct.fit_transform(X))

In [39]:
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


# encoding the dependent variable 


In [40]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder() 
y = le.fit_transform(y) 


In [41]:
print(y)


[0 1 0 0 1 1 0 1 0 1]


## spliting the testing and train sets 


In [42]:
from sklearn.model_selection import train_test_split
X_trian, X_test, Y_train, Y_test = train_test_split(x,y,test_size =0.2)

In [43]:
print(X_trian) 

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 0.0 37.0 67000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [0.0 0.0 1.0 27.0 48000.0]]


In [44]:
print(X_test)

[[1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]]


In [45]:
 print(Y_train, Y_test)
    

[0 0 1 0 0 1 1 1] [1 0]


## Feature scalling



In [49]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_trian[:,3:] = sc.fit_transform(X_trian[:,3:])
X_test[:,3:] = sc.transform(X_test[:,3:])


In [50]:
print(X_trian) 

[[0.0 1.0 0.0 -1.2135263330767379 -0.7263737252004268]
 [1.0 0.0 0.0 1.5169079163459227 1.6629164977938717]
 [1.0 0.0 0.0 -0.23837124399721624 -0.19542034231280486]
 [0.0 0.0 1.0 0.4984126010850891 -0.9918504166442377]
 [0.0 0.0 1.0 0.34672180945049674 0.20279469485291157]
 [1.0 0.0 0.0 0.1516907916345924 0.9992247691843444]
 [0.0 1.0 0.0 0.7367838450823053 0.571512321858205]
 [0.0 0.0 1.0 -1.7986193865244509 -1.5228037995318595]]


In [51]:
print(X_test
     ) 

[[1.0 0.0 0.0 2.29703198760954 2.59208491784721]
 [0.0 1.0 0.0 2.6870940232413485 3.123038300734832]]
