# Artificial Neural Network

### Importing the libraries

In [48]:
!pip install tensorflow

In [49]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [50]:
tf.__version__

'2.9.1'

## Part 1 - Data Preprocessing

### Importing the dataset

In [51]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [52]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [53]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder() 
X[:,2 ] = le.fit_transform(X[:,2]) 

In [54]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [55]:
from sklearn.compose import ColumnTransformer 
from sklearn.preprocessing import OneHotEncoder 
ct = ColumnTransformer(transformers=[('endcoder', OneHotEncoder(),[1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [56]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [57]:
from sklearn.model_selection import train_test_split
X_trian, X_test, Y_train, Y_test = train_test_split(X,y,test_size =0.2)

### Feature Scaling

In [58]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
#taking all columns because feature scalling is Extremely important to deep learning 
X_trian = sc.fit_transform(X_trian)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [59]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [60]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [61]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [62]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [63]:
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

### Training the ANN on the Training set

In [64]:
ann.fit(X_trian, Y_train, batch_size=32, epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 809us/step - loss: 0.5207 - accuracy: 0.7760
Epoch 2/100
250/250 [==============================] - 0s 791us/step - loss: 0.4646 - accuracy: 0.7999
Epoch 3/100
250/250 [==============================] - 0s 766us/step - loss: 0.4453 - accuracy: 0.8083
Epoch 4/100
250/250 [==============================] - 0s 731us/step - loss: 0.4350 - accuracy: 0.8133
Epoch 5/100
250/250 [==============================] - 0s 768us/step - loss: 0.4278 - accuracy: 0.8192
Epoch 6/100
250/250 [==============================] - 0s 755us/step - loss: 0.4223 - accuracy: 0.8236
Epoch 7/100
250/250 [==============================] - 0s 748us/step - loss: 0.4178 - accuracy: 0.8269
Epoch 8/100
250/250 [==============================] - 0s 886us/step - loss: 0.4142 - accuracy: 0.8289
Epoch 9/100
250/250 [==============================] - 0s 849us/step - loss: 0.4114 - accuracy: 0.8305
Epoch 10/100
250/250 [==============================] - 0s 813us/step - l

250/250 [==============================] - 0s 831us/step - loss: 0.3324 - accuracy: 0.8652
Epoch 80/100
250/250 [==============================] - 0s 788us/step - loss: 0.3321 - accuracy: 0.8634
Epoch 81/100
250/250 [==============================] - 0s 833us/step - loss: 0.3320 - accuracy: 0.8655
Epoch 82/100
250/250 [==============================] - 0s 800us/step - loss: 0.3309 - accuracy: 0.8648
Epoch 83/100
250/250 [==============================] - 0s 822us/step - loss: 0.3310 - accuracy: 0.8655
Epoch 84/100
250/250 [==============================] - 0s 855us/step - loss: 0.3312 - accuracy: 0.8646
Epoch 85/100
250/250 [==============================] - 0s 842us/step - loss: 0.3307 - accuracy: 0.8661
Epoch 86/100
250/250 [==============================] - 0s 793us/step - loss: 0.3304 - accuracy: 0.8646
Epoch 87/100
250/250 [==============================] - 0s 777us/step - loss: 0.3301 - accuracy: 0.8655
Epoch 88/100
250/250 [==============================] - 0s 776us/step - loss:

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer ?

**Solution**

In [69]:
prediction = np.array([[1,0,0, 600, 1, 40, 3, 60000, 2, 1, 0, 50000]])

prediction = sc.transform(prediction)
print(ann.predict(prediction) > 0.5)

1/1 [==============================] - 0s 18ms/step
[[False]]


Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [76]:
y_pred = ann.predict(X_test)
y_pred = (y_pred> 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), Y_test.reshape(len(Y_test),1)),1))

63/63 [==============================] - 0s 1ms/step
[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [78]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, y_pred)
print(cm)
accuracy_score(Y_test, y_pred)

[[1536   63]
 [ 230  171]]


0.8535